export enum SavedStateValueType {
    Undefined = 0,
    String = 1,
    HexString = 2,
    Boolean = 3,
    Integer = 4,
    BigNumber = 5,
    Array = 6,
    Set = 7,
    Object = 8,
    Null = 9,
    Signed = 10,
    Decimal = 11,
    SignedBigNumber = 12,
}
